import test from 'node:test';
import assert from 'node:assert/strict';
import { handleInquiry } from '../src/worker.js';
const payload={address:'Testobjekt 1, Hamburg',email:'visitor@example.com',caretaker:'',website:'',requestId:'77f082cb-3b56-47f2-a1c4-3833d5649b10'};
const env={RESEND_API_KEY:'test-key',INQUIRY_TO:'owner@example.com',INQUIRY_LIMITER:{limit:async()=>({success:true})}};
const request=(data=payload,headers={})=>new Request('https://site.example/api/inquiry',{method:'POST',headers:{Origin:'https://site.example','Content-Type':'application/json',...headers},body:JSON.stringify(data)});
const noSend=()=>{throw new Error('Provider must not be called');};
test('valid inquiry has fixed recipient and visitor reply-to',async()=>{let sent;const res=await handleInquiry(request({...payload,to:'attacker@example.com'}),env,async(url,init)=>{assert.equal(url,'https://api.resend.com/emails');sent=JSON.parse(init.body);assert.equal(init.headers['Idempotency-Key'],'seehafer-inquiry/'+payload.requestId);return Response.json({id:'provider-id'});});assert.equal(res.status,200);assert.deepEqual(sent.to,['owner@example.com']);assert.equal(sent.reply_to,payload.email);assert.equal((await res.json()).emailId,'provider-id');});
test('cross-origin submissions are rejected',async()=>assert.equal((await handleInquiry(request(payload,{Origin:'https://other.example'}),env,noSend)).status,403));
test('missing origin is rejected',async()=>{const req=request();req.headers.delete('Origin');assert.equal((await handleInquiry(req,env,noSend)).status,403);});
test('invalid email and header injection are rejected',async()=>{for(const email of ['bad','x@example.com\r\nBcc:someone@example.com'])assert.equal((await handleInquiry(request({...payload,email}),env,noSend)).status,400);});
test('oversized fields and bodies are rejected',async()=>{for(const address of ['x'.repeat(251),'x'.repeat(5000)])assert.equal((await handleInquiry(request({...payload,address}),env,noSend)).status,400);});
test('honeypot rejects bot submission',async()=>assert.equal((await handleInquiry(request({...payload,website:'spam'}),env,noSend)).status,400));
test('GET is rejected',async()=>assert.equal((await handleInquiry(new Request('https://site.example/api/inquiry'),env,noSend)).status,405));
test('rate limit prevents provider invocation',async()=>assert.equal((await handleInquiry(request(),{...env,INQUIRY_LIMITER:{limit:async()=>({success:false})}},noSend)).status,429));
test('unconfigured delivery is not reported as sent',async()=>assert.equal((await handleInquiry(request(),{...env,RESEND_API_KEY:''},noSend)).status,503));
test('provider error and network failure are not reported as sent',async()=>{assert.equal((await handleInquiry(request(),env,async()=>Response.json({message:'secret provider detail'},{status:403}))).status,502);const res=await handleInquiry(request(),env,async()=>{throw new Error('network');});assert.equal(res.status,502);assert.ok(!(await res.text()).includes('test-key'));});
test('retry uses same provider idempotency key',async()=>{const keys=[];const send=async(_,init)=>{keys.push(init.headers['Idempotency-Key']);return Response.json({id:'same'});};await handleInquiry(request(),env,send);await handleInquiry(request(),env,send);assert.equal(keys[0],keys[1]);});

import { callbackSlots } from '../public/callback-slots.js';
test('callback slots skip weekends, use Berlin time and exclude started windows',()=>{
  const slots=callbackSlots(new Date('2026-10-02T14:30:00Z'));
  assert.equal(slots[0].value,'2026-10-05');
  assert.ok(slots.length >= 40);
  assert.deepEqual(callbackSlots(new Date('2026-09-29T08:30:00Z'))[0].windows.map(w=>w.value),['11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30']);
});
const callback=()=>({kind:'callback',name:'TEST Rückruf',phone:'+49 40 1234567',day:callbackSlots()[0].value,time:callbackSlots()[0].windows[0].value,requestId:payload.requestId});
test('callback delivers name, phone and requested Berlin window to fixed inbox',async()=>{let sent;const res=await handleInquiry(request(callback()),env,async(_,init)=>{sent=JSON.parse(init.body);return Response.json({id:'callback-id'});});assert.equal(res.status,200);assert.deepEqual(sent.to,['owner@example.com']);assert.ok(sent.text.includes('+49 40 1234567'));assert.ok(sent.text.includes('Europe/Berlin'));assert.ok(sent.subject.startsWith('Rückrufwunsch'));assert.equal(sent.reply_to,undefined);});
test('callback rejects stale dates, weekends, arbitrary times and invalid phone',async()=>{for(const bad of [{day:'2000-01-01'},{time:'03:00'},{phone:'hello'},{name:''},{phone:'123456\r\nBcc: x'}])assert.equal((await handleInquiry(request({...callback(),...bad}),env,noSend)).status,400);});
test('callback calendar spans future months with half-hour windows',()=>{const days=callbackSlots(new Date('2026-09-29T08:30:00Z'));assert.ok(days.some(d=>d.value==='2026-11-27'));assert.equal(days.some(d=>d.value==='2026-10-03'),false);assert.equal(days.at(-1).value,'2026-11-27');assert.equal(days[1].windows.length,16);});
test('callback schedule follows Berlin winter time and one-hour notice',()=>{const days=callbackSlots(new Date('2026-10-26T08:10:00Z'));assert.equal(days[0].windows[0].value,'10:30');});
test('callback rejects requests outside supported future range',async()=>assert.equal((await handleInquiry(request({...callback(),day:'2099-01-01'}),env,noSend)).status,400));
test('immediate callback needs no appointment and identifies urgency in email',async()=>{let sent;const data={...callback(),timing:'asap'};delete data.day;delete data.time;const res=await handleInquiry(request(data),env,async(_,init)=>{sent=JSON.parse(init.body);return Response.json({id:'asap-id'});});assert.equal(res.status,200);assert.match(sent.subject,/Sofortiger/);assert.match(sent.text,/so schnell wie möglich/);assert.ok(!sent.text.includes('undefined'));});
test('immediate callback still validates contact and rejects unknown timing',async()=>{for(const bad of [{phone:'x'},{name:''},{timing:'urgent'}])assert.equal((await handleInquiry(request({...callback(),timing:'asap',...bad}),env,noSend)).status,400);});
