import {test} from 'node:test';import assert from 'node:assert/strict';
import {createIntakeToken,verifyIntakeToken,handleIntake,validateAttachments} from '../src/intake.js';
import {validateIntake} from '../public/intake-schema.js';
const id='11111111-1111-4111-8111-111111111111',secret='test-only-secret';
const data={name:'Test',company:'Test Verwaltung',email:'test@example.com',role:'Hausverwaltung',address:'Testweg 1, 20000 Hamburg',systems:['Weiß ich nicht'],siteContact:'Noch nicht bekannt',coordination:'Bitte zuerst mit mir abstimmen',recipient:'Test Eigentümer',nextStep:'Bitte per E-Mail weiter abstimmen'};
const env={INTAKE_SECRET:secret,RESEND_API_KEY:'fake',INQUIRY_TO:'internal@example.com',INQUIRY_LIMITER:{limit:async()=>({success:true})}};
async function request(patch={},path='/api/intake'){return new Request('https://test.example'+path,{method:'POST',headers:{Origin:'https://test.example','Content-Type':'application/json'},body:JSON.stringify({token:await createIntakeToken(secret,id),requestId:id,consent:true,data,...patch})});}
test('signed invitation expires and rejects tampering',async()=>{const t=await createIntakeToken(secret,id,0);assert.equal((await verifyIntakeToken(secret,t,1000)).id,id);assert.equal(await verifyIntakeToken(secret,t,31*86400000),null);assert.equal(await verifyIntakeToken(secret,t+'x',1000),null);assert.equal(await verifyIntakeToken('wrong',t,1000),null);});
test('core fields suffice and invalid dates do not throw',()=>{assert.deepEqual(validateIntake(data).errors,{});assert.ok(validateIntake({...data,deadline:'2026-99-99'}).errors.deadline);assert.ok(validateIntake({...data,systems:['forged']}).errors.systems);});
test('callback requires phone and upcoming weekday; stale conditional data removed',()=>{assert.ok(validateIntake({...data,nextStep:'Bitte schnellstmöglich anrufen'}).errors.phone);assert.ok(validateIntake({...data,phone:'012345678',nextStep:'Bitte zu meiner Wunschzeit anrufen',callDate:'2026-10-03',callWindow:'09–12 Uhr'},new Date('2026-09-29')).errors.callDate);assert.equal(validateIntake({...data,callDate:'invalid',siteEmail:'invalid'}).clean.siteEmail,'');assert.deepEqual(validateIntake({...data,callDate:'invalid',siteEmail:'invalid'}).errors,{});});
test('attachments restricted to files with supported signatures and total size',()=>{assert.throws(()=>validateAttachments([{content:btoa('<script>')} ]));assert.throws(()=>validateAttachments(Array(4).fill({content:btoa('%PDF-test')})));assert.equal(validateAttachments([{content:btoa('%PDF-test')}])[0].filename,'unterlage-1.pdf');});
test('valid intake uses fixed inbox and stable idempotency, includes structured record',async()=>{let sent;const r=await handleIntake(await request(),env,async(url,options)=>{sent=options;return Response.json({id:'provider-id'});});assert.equal(r.status,200);const mail=JSON.parse(sent.body);assert.deepEqual(mail.to,['internal@example.com']);assert.equal(mail.reply_to,data.email);assert.equal(sent.headers['Idempotency-Key'],'seehafer-intake/'+id);const packet=JSON.parse(Buffer.from(mail.attachments[0].content,'base64'));assert.equal(packet.invitationId,id);assert.equal(packet.data.address,data.address);});
test('invalid token, missing consent, and invalid fields never send',async()=>{for(const patch of [{token:'bad'},{consent:false},{data:{}}]){const r=await handleIntake(await request(patch),env,()=>{throw Error('should not send')});assert.ok([400,403].includes(r.status));}});
test('verification does not send; provider failures never claim success',async()=>{assert.equal((await handleIntake(await request({},'/api/intake/verify'),env)).status,200);assert.equal((await handleIntake(await request(),env,async()=>new Response('',{status:500}))).status,502);assert.equal((await handleIntake(await request(),{...env,INQUIRY_LIMITER:{limit:async()=>({success:false})}})).status,429);});
